/**
 * Generates the minimal wrapper file for project integration.
 * Creates a thin wrapper that loads AI Debug from node_modules.
 *
 * @returns {string} JavaScript wrapper code
 *
 * Features:
 * - Lazy loading in non-production environments
 * - Graceful fallback if initialization fails
 * - Custom templates directory support
 * - Production removal patterns
 *
 * The wrapper provides:
 * - debug.wrap() - Main debugging method
 * - debug.raw() - Raw object inspection
 * - debug.log() - Manual logging
 * - REMOVAL_PATTERNS - Regex for production builds
 *
 * @example
 * const wrapperCode = generateWrapper();
 * writeFileSync('.ai-debug/wrapper.js', wrapperCode);
 */
export function generateWrapper(): string {
  return `// AI Debug Wrapper - Generated by @dkmaker/ai-debug
// This file provides a thin wrapper around the AI Debug package

let debugger = null;

// Initialize on first import
(async () => {
  if (process.env.NODE_ENV !== 'production') {
    try {
      const { AIDebug } = await import('@dkmaker/ai-debug');
      const { readFileSync } = await import('node:fs');
      const { join, dirname } = await import('node:path');
      
      // Load configuration
      const configPath = join(process.cwd(), '.ai-debug', 'config.json');
      const config = JSON.parse(readFileSync(configPath, 'utf-8'));
      
      // Initialize debugger with custom templates path
      const customTemplatesPath = join(process.cwd(), '.ai-debug', 'templates');
      debugger = new AIDebug(config, customTemplatesPath);
    } catch (e) {
      console.warn('Failed to initialize AI Debug:', e.message);
    }
  }
})();

// Export wrapper functions
/**
 * Debug wrapper object with safe fallbacks.
 * Methods gracefully degrade if debugger not initialized.
 */
export const debug = {
  wrap: (action, fn, ...args) => debugger?.wrap(action, fn, ...args) || fn(),
  raw: (action, fn, ...args) => debugger?.raw(action, fn, ...args) || fn(),
  log: (level, message, data) => debugger?.log(level, message, data),
};

// Export removal patterns for production builds
/**
 * Regular expressions for removing debug code in production.
 * Use with build tools to strip debug blocks.
 */
export const REMOVAL_PATTERNS = {
  debugBlock: /\\/\\*DEBUG:START\\*\\/[\\s\\S]*?\\/\\*DEBUG:END\\*\\//g,
  inlineDebug: /\\/\\*DEBUG:START\\*\\/.*?\\/\\*DEBUG:END\\*\\//g,
};
`;
}
